version: '3.6'
services:
  web:
    image: nginx:latest
    container_name: sample-web-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/usr/share/nginx/html
    ports: ["8080:80"]

